travis:
  secure:
    BINSTAR_TOKEN: Trp9xbc94nQmwn7MLzaCI430vzkm5Ao7Sh8P99Fa4/kNseCy1HVXffZF+mWesaFRP/h9F/Y9JvO/9LomAuOqrroQeYE5Jv3PNUT1y0ovcY42ebtXObdE6eDjZgx4opfMs/6QbC47nREcx6Fe8u4tfPOCyCxSrWUC3lXWKSgn3k/jyhmEWCYtFOGFywWKj1MI0ct+av6l3YfIMm1ccdZcYdhcGDCpRXC/NAhQHMZ4f5UZfEGsOCryLmGX9UPUx9H8k2rli5DIgnQJ0tjK8YttSJ1gUE8eq4C3upcvc4Bbr4MkJ5hKrb/fWNhrfWTgZrR8NcuizjRVPhzJdbg556q18fdQ13h99WbLcI2yaCuxO5w4ukxScQ6t5VSpNM6JfaZ3681nO9Ne1JZ1KtjbXUEg5wByfRmJzJsMPrxvozY+Oy++UR0C+SyaROYmLtc/N0zOwWOvwDcsdg3E4RxZEaGf3TT6owaVmRpq9C7GRjRp5Tzzw/GvXD65beXlv6fJhpjgtrDZE0qwlWumqwJGCdQThG9OQj3XgJ7gCh2416slgbo2abY2VXE/99Futoxe70ZBM+JJ2RWgIRwGS3Qe0AhDitQ9AEIy1T00kabS0EYTyubcyNbWJvM55ohyRqBT6mYcq4MRaK8WqiuA79dBZVXnVhkm+pEmwvNpkodD3WDsu1U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
